services:
  bot:
    image: teeseal/musen
    container_name: musen
    restart: unless-stopped
    depends_on: [lavalink]
    environment:
      - TOKEN
      - LAVALINK_HOST=lavalink
      - LAVALINK_PORT=2333
      - LAVALINK_PASSWORD=password
  lavalink:
    image: fredboat/lavalink:latest
    container_name: lavalink
    expose: [2333]
    environment:
      - LAVALINK_SERVER_PASSWORD=password
    volumes:
      - ./lavalink-config.yml:/opt/Lavalink/application.yml
